const ADD_ITEM = "ADD_ITEM";
const UPDATE_ITEM = "UPDATE_ITEM";
const REMOVE_ITEM = "REMOVE_ITEM";
const SHOW_SECTION = "SHOW_SECTION";
const HIDE_SECTION = "HIDE_SECTION";

export default {
  ADD_ITEM,
  UPDATE_ITEM,
  REMOVE_ITEM,
  SHOW_SECTION,
  HIDE_SECTION,
};
